name: Example Bank API Branch Workflow

on:
  push:
    branches-ignore:
      - develop
    tags-ignore:
      - '*'

jobs:
  docker-build-for-branch:
    name: Docker Build and Push For API Branch
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
      SERVICE_NAME: openg2p-g2p-bridge-example-bank-api
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')

          IMAGE_ID=$NAMESPACE/$SERVICE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$BRANCH_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV
          echo VERSION=$VERSION >> $GITHUB_ENV

          docker build ./openg2p-g2p-bridge-example-bank-api -f ./openg2p-g2p-bridge-example-bank-api/Dockerfile-git \
            --tag $IMAGE_ID:$VERSION
          if [[ '${{ secrets.docker_hub_token }}' != '' && '${{ secrets.docker_hub_actor }}' != '' ]]; then
            export DOCKER_PUSH="true"
            echo DOCKER_PUSH=$DOCKER_PUSH >> $GITHUB_ENV
          fi
      - name: Docker push
        if: env.DOCKER_PUSH == 'true'
        run: |
          echo "${{ secrets.docker_hub_token }}" | docker login -u ${{ secrets.docker_hub_actor }} --password-stdin
          docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}

  openapi-publish:
    name: OpenAPI Generate and Publish For API Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name (merge)
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')
          echo BRANCH_NAME=$BRANCH_NAME >> $GITHUB_ENV
      - name: Setup python for openapi generate
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install app
        run: |
          python -m pip install git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.1\#subdirectory=openg2p-fastapi-common
          python -m pip install git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.1\#subdirectory=openg2p-fastapi-auth
          python -m pip install git+https://github.com/openg2p/openg2p-g2p-bridge-example-bank@v1.0.2\#subdirectory=openg2p-g2p-bridge-example-bank-models
          python -m pip install openg2p-g2p-bridge-example-bank-api==1.1.0
      - name: Generate openapi json
        run: |
          mkdir -p openg2p-g2p-bridge-example-bank-api/api-docs/generated
          python3 openg2p-g2p-bridge-example-bank-api/main.py getOpenAPI openg2p-g2p-bridge-example-bank-api/api-docs/generated/openapi.json
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Publish to stoplight
        run: |
          npx @stoplight/cli@5 push --ci-token ${{ secrets.STOPLIGHT_PROJECT_TOKEN }} --url https://openg2p.stoplight.io --branch ${{ env.TAG_NAME }} --directory openg2p-g2p-bridge-example-bank-api/api-docs/generated
